### ISSUE TITLE
Update funktioniert nicht richtig

### ISSUE THREAD

**Issue by romefi** [agiktsh/ch.sh.oereb_server.database.2.oereb_themes#3]
Ich habe noch ein paar XTF aufbereitet, vor allem Nutzungsplanung und Lärmempfindlichkeitsstufen, Alle XTFs wurden durch mgdm2oereb aufbereitet, in https://github.com/agiktsh/oereb-server.database/tree/master abgelegt und sehen nach meinem Empfinden gut aus. Es werden auch alle XTFs beim Workflow gelesen und auch die importierten Objekte ausgewiesen (https://github.com/agiktsh/oereb-server.database/actions/runs/5244314356/jobs/9470497376).

Jedoch erscheinen die Daten nicht im DataExtract (z.B. https://github.com/agiktsh/oereb-server.database/blob/master/ch.Laermempfindlichkeitsstufen-Laermempfindlichkeitsstufen_V1_2-ch.2914.Laermempfindlichkeitsstufen.xtf oder https://github.com/agiktsh/oereb-server.database/blob/master/ch.Nutzungsplanung-Nutzungsplanung_V1_2-ch.2914.Nutzungsplanung.xtf)

Mache ich etwas falsch?

**Comment by vvmruder** [comment]
Also ich habe jetzt nochmal einen vollen Rebuild laufen lassen. Dabei konnte ich sehen, dass es beim https://raw.githubusercontent.com/agiktsh/oereb-server.database/master/ch.Nutzungsplanung-Nutzungsplanung_V1_2-ch.2951.Nutzungsplanung.OeREBKRMtrsfr_V2_0.xtf abbricht mit dem DB Import. Kurz geschaut und gefunden, dass keine Verknüpften Legendeneinträge und Darstellungsdienste drin sind. Es handelt sich beispielsweise um eigentumsbeschraenkung_b2ce789c-455b-413c-b472-690c3ca220aa.

Das ist sh.beg.211.0.11 und dieser Artcode ist in eurem Katalog nicht zu finden: https://models.geo.sh.ch/AGI/OeREB/ch.sh.OeREBKRMlegdrst_V2_0.xml 

Nicht mit inKraft oder sonst. Fehlt diese Gemeinde noch im Katalog?

**Comment by romefi** [comment]
Hab die Gemeinde gelöscht und läuft wieder durch. Aber die Daten erscheinen immer noch nicht im DataExtract.

Den Katalog werde ich noch anschauen.

**Comment by vvmruder** [comment]
Ohje.. hab den Fehler gefunden. Momentan ist das Deployment noch wie einen Sack Flöhe zu hüten. Auf eurem Server läuft ein spezieller Service, der alle 30 Sekunden nachschaut ob es eine neue Version der DB gibt. Den habe ich nicht wieder angeworfen nach den Anpassungen an der HDD-Grösse auf dem Server.

**Comment by vvmruder** [comment]
@romefi Bitte noch prüfen und allenfalls dann hier kommentieren oder schliessen. => THX

**Comment by romefi** [comment]
Hat geklappt, danke
