### ISSUE TITLE
DataExtract zeigt in einem Ortsteil nichts an

### ISSUE THREAD

**Issue by romefi** [agiktsh/ch.sh.oereb_server.database.2.oereb_themes#5]
@vvmruder Der DataExtract https://oereb.sh.opengis.ch/extract/xml/?GEOMETRY=true&EGRID=CH351308705467 zeigt bei mir nichts an. Komischerweise geht keines in einem bestimmten Ortsteil. Im Log wird auch nichts angezeigt, dachte liegt vielleicht an unserem Katalog.

Hast du eine Möglichkeit herauszufinden, wieso die DataExtracts von diesem Ortsteil nicht gehen?

**Comment by romefi** [comment]
@vvmruder Fehler gefunden, die Gemeinde fehlte im Katalog in der Tabelle GemeindeMItOeREBK

**Comment by romefi** [comment]
@vvmruder Ist doch ein Problem. Habe gemerkt, dass keiner der Ortsteile funktioniert. Es wird kein DataExtract angezeigt. Früher hat das sicher mal funktioniert. Vielleicht hat @edigonzales etwas angepasst und wir müssten das in unseren Katalogen nachtragen?

**Comment by edigonzales** [comment]
@romefi @vvmruder 

```
SELECT grundlagedatenstand from live.oerbkrmvs_v2_0konfiguration_gemeindemitoerebk WHERE gemeinde=2934
```

liefert nichts zurück. Scheint aber momentan komplett empty zu sein, dieses Attribut:

![Screenshot 2023-07-24 at 11 42 52](https://github.com/agiktsh/oereb-server.database/assets/2767800/67289da1-d9b2-43b7-bc38-86c613c13dfe)

So sieht das bei uns aus:

![Screenshot 2023-07-24 at 11 45 33](https://github.com/agiktsh/oereb-server.database/assets/2767800/7eaed589-3298-415b-8ff1-d8c437529a6f)

**Comment by romefi** [comment]
@edigonzales Kommen die Gemeinden, die es offiziell nicht mehr gibt und fusioniert haben, aber immer noch ein eigenes Nutzumgsplanungs-Operat haben, auch dort rein? 2934 ist als Grunbuchkreis von 2939 erfasst. 

Oder wie müssen wir das richtig angeben?

**Comment by vvmruder** [comment]
Ich habe mal den Build hier nochmal ausgelöst. Der Katalog ist ja im Basisimage https://github.com/openoereb/ch.sh.oereb_base wo du @romefi es ja richtigerweise angepasst hast. Danach muss noch das Image aus diesem Repo aktualisiert werden. Die patentierte Schichtentorte... :)

**Comment by vvmruder** [comment]
@romefi der Build ist durch und die neue Version bereits auf dem Service ausgerollt. Kannst du mal prüfen?

**Comment by romefi** [comment]
@vvmruder Jetzt tut es wieder, danke. Das Problem war offensichtlich, dass wir vorher im Grundbuchkreis nicht auf die richtige Gemeinde verwiesen haben (also 2934 auf 2939). Das hatte ich heute Morgen angepasst im Katalog, aber in dem Fall den Build nicht sauber durch alle Schichten aktualisiert :)

Ich hatte diesen Workflow mit Flag=1 gestartet: https://github.com/openoereb/ch.sh.oereb_base/actions/workflows/ch.sh.oereb_base.sync.yml

Was hatte ich vergessen, um den Build vollständig auszurollen?

**Comment by vvmruder** [comment]
nur anschliessend hier in diesem Repo nochmal build auslösen-später schalten wir das dann durchgängig automatisch

**Comment by edigonzales** [comment]
> @edigonzales Kommen die Gemeinden, die es offiziell nicht mehr gibt und fusioniert haben, aber immer noch ein eigenes Nutzumgsplanungs-Operat haben, auch dort rein? 2934 ist als Grunbuchkreis von 2939 erfasst.
> 
> Oder wie müssen wir das richtig angeben?

Geht ja jetzt wieder. Falls die Frage sonstwie relevant ist: Das ist unabhängig von diesen "Konfig-Tabellen" in der DB, sondern eigentlich nur über die Geometrie definiert. Wie du die Operate schickst, ist nicht vorgegeben. Kann zum Problem werden (hatte/haben wir glaubs), wenn es eine fusionierte Gemeinde gibt, wo ein Teil noch keine digitale Ortsplanung hatte. Ist dann bissle unschön bis falsch. 

Grundbuchkreis wird über den NBIdent ermittelt: NBIdent des Grunstückes = NBIdent aus der Grundbuchkreis-Tabelle.

**Comment by romefi** [comment]
Danke @edigonzales für die Erklärung. So in etwa hatte ich mir das auch gedacht. Und funktioniert ja auch wenn man weiss wie man den Build richtig macht :)

Danke euch für die Unterstützung.
