### ISSUE TITLE
Bezeichnung Grundbuch in PDF fehlt

### ISSUE THREAD

**Issue by romefi** [agiktsh/ch.sh.oereb_server.database.2.oereb_themes#7]
@vvmruder Im Auszug beim Kanton Solothurn wird auf der ersten Seite im PDF die Zeile Grundbuch auch mit "Grundbuch" bezeichnet

![image](https://github.com/agiktsh/oereb-server.database/assets/26796989/b582bc35-5080-40cc-9433-6af0410abc31)

In unserem PDF-Auszug ist die Bezeichnung leer
 
![image](https://github.com/agiktsh/oereb-server.database/assets/26796989/745ab28b-f219-4a53-9d84-cc3983ca8b64)

Hast du eine Idee, woran das liegen könnte?

**Comment by romefi** [comment]
@edigonzales da das wahrscheinlich sowieso die Runde über dich macht. Weisst du, wo wir die Bezeichnung für das PDF konfigurieren können?

**Comment by edigonzales** [comment]
@romefi Auch zu den "GemeindenMitOerebK" zum Attribut "bezeichnungunterheinheitgrundbuch":

![Screenshot 2023-07-25 at 13 30 23](https://github.com/agiktsh/oereb-server.database/assets/2767800/a33517e9-32a5-4a6d-8e00-1bd94447f5ef)

**Comment by romefi** [comment]
Alles klar, danke 🙏
